//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenBay()
        {
            this.DatVes = new HashSet<DatVe>();
        }
    
        public int MaChuyenBay { get; set; }
        public string SoHieuChuyenBay { get; set; }
        public int MaSanBayDi { get; set; }
        public int MaSanBayDen { get; set; }
        public System.DateTime GioKhoiHanh { get; set; }
        public System.DateTime GioDen { get; set; }
        public string HangHangKhong { get; set; }
        public decimal Gia { get; set; }
        public int SoGheTrong { get; set; }
    
        public virtual SanBay SanBay { get; set; }
        public virtual SanBay SanBay1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatVe> DatVes { get; set; }
    }
}
