//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLVEMAYBAYEntities : DbContext
    {
        public QLVEMAYBAYEntities()
            : base("name=QLVEMAYBAYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuyenBay> ChuyenBays { get; set; }
        public virtual DbSet<DatVe> DatVes { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<SanBay> SanBays { get; set; }
        public virtual DbSet<ThanhToan> ThanhToans { get; set; }
    }
}
